import Head from "next/head";
import { ReactElement } from "react";
import { useQuery } from "react-query";
import { Layout } from "../components/Layout";
import { NextPageWithLayout } from "./_app";

export const useTodos = () => {
  return useQuery("todos", () =>
    fetch("https://jsonplaceholder.typicode.com/todos/1").then((r) => r.json())
  );
};
const Index: NextPageWithLayout = () => {
  const { isLoading, error, data } = useTodos();

  if (error instanceof Error) {
    return <p>An error has occurred: {error.message}</p>;
  }

  return (
    <div>
      <Head>
        <title>Create Cool Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-lg text-red-600">Hello world</p>
      <h2>Api data:</h2>
      {isLoading && <p>Loading ...</p>}
      <p>{data?.title}</p>
    </div>
  );
};

Index.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Index;
